openapi: 3.0.3
info: 
    title: SamSebeMehanik
    description: API для проекта
    version: 1.0.0
    contact:
        name: Project
        email: email@email.email
    license:
        name: MIT
servers: 
    - url: http://localhost:8080
paths: 
    /api/v1/autocomponents:
        post:
            summary: Создать компонент с уникальным id
            tags: [компонент]
            security: 
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ComponentCreateRequest'
                        example:
                          "name": "Двигатель"
                          "description": "Сердце автомобиля. Преобразует химическую энергию топлива (бензина, дизеля, газа) в механическую работу путём его сжигания непосредственно внутри рабочих цилиндров"
                          "specification": "Смесь топлива и воздуха сгорает внутри цилиндров, создавая высокое давление, которое толкает поршень, а тот вращает коленвал"
                          "specification_jsonB": null
            responses:
                '201':
                    description: Компонент создан
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ComponentCreateResponse' 
                '400':
                    description: Ошибка валидации
                    content:
                        application/json:
                            schema:
                               $ref: '#/components/schemas/ComponentErrorResponse' 
                '500':
                    description: Внутренняя ошибка сервера
                    content:
                        application/json:
                            schema:
                               $ref: '#/components/schemas/ComponentErrorResponse'
    /api/v1/autocomponents/{id}:
        put:
            summary: Отредактировать компонент с указанным id
            tags: [компонент]
            security:
                - bearerAuth: []
            parameters:
                - name: id
                  in: paths
                  required: true
                  schema:
                    type: string
                    format: uuid
                    
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ComponentEditRequest'
                        example:
                          "name": "Двигатель"
                          "description": "Разновидность теплового двигателя, в котором топливная смесь сгорает непосредственно в рабочей камере (внутри) двигателя."
                          "specification": "Продукты сгорания образуют рабочее тело. Такой двигатель является первичным, химическим, и преобразует энергию сгорания топлива в механическую работу."
                          "specification_jsonB": null
            responses:
                '200':
                    description: Компонент изменен успешно
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ComponentEditResponse' 
                '400':
                    description: Ошибка валидации
                    content:
                        application/json:
                            schema:
                               $ref: '#/components/schemas/ComponentErrorResponse' 
                '500':
                    description: Внутренняя ошибка сервера
                    content:
                        application/json:
                            schema:
                               $ref: '#/components/schemas/ComponentErrorResponse'
                '404':
                    description: Ресурс не найден
                    content:
                        application/json:
                            schema:
                               $ref: '#/components/schemas/ComponentErrorResponse' 
components:
    schemas:
        ComponentCreateRequest:
            type: object
            required: [name]
            properties:
                name:
                    type: string
                    minLength: 2
                description:
                    type: string
                specification:
                    type: string
                specification_jsonB:
                    type: object
                    additionalProperties: true
        ComponentCreateResponse:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                    readOnly: true
                name:
                    type: string
                description:
                    type: string
                specification:
                    type: string
                specification_jsonB:
                    type: object
                    additionalProperties: true
        ComponentErrorResponse:
            type: object
            properties:
                code: 
                    type: string
                message:
                    type: string
                details:
                    type: array
                    items:
                        type: string
        ComponentEditRequest:
            type: object
            required: [name]
            properties:
                name:
                    type: string
                    minLength: 2
                description:
                    type: string
                specification:
                    type: string
                specification_jsonB:
                    type: object
                    additionalProperties: true
        ComponentEditResponse:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                    readOnly: true
                name:
                    type: string
                description:
                    type: string
                specification:
                    type: string
                specification_jsonB:
                    type: object
                    additionalProperties: true
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: jwt
