@startuml
actor Администратор
actor Пользователь 

Администратор --|> Пользователь
Администратор --> (Редактирование сущности)
Администратор --> (Просмотр версий сущности)
Администратор --> (Управление версиями сущности)
Пользователь --> (Авторизация)
Пользователь --> (Просмотр сущности)
Пользователь --> (Добавление в избранное)
Пользователь --> (Просмотр списка избранного)
Пользователь --> (Поиск сущности)
(Редактирование сущности) ..> (Авторизация) : << include>>
(Просмотр версий сущности) ..> (Авторизация) : << include >>
(Управление версиями сущности) ..> (Авторизация) : << include >>
@enduml
