#### 1. Редактирование сущности

@startuml

actor Администратор
participant Frontend
participant Backend
participant KafkaBroker
database PostgreSQL
database MongoDB

== WebSocket подключение ==

Frontend -> Backend : WS handshake (/ws)
Frontend -> Backend : SUBSCRIBE /topic/components

== Редактирование компонента ==

Администратор -> Frontend : Нажать "Сохранить"
Frontend -> Backend : PUT /api/v1/component/{id}

Backend -> PostgreSQL : UPDATE component
PostgreSQL --> Backend : OK

Backend -> MongoDB : save version
MongoDB --> Backend : OK

Backend -> KafkaBroker : publish ComponentUpdated event
Backend --> Frontend : HTTP 200 OK

== Асинхронное уведомление ==

KafkaBroker ->> Backend : deliver ComponentUpdated event
Backend ->> Frontend : push via WebSocket (/topic/components)

@enduml

#### 2. Добавление в избранное.
@startuml

title Добавление в избранное

Actor User
participant UI
participant FavouritesController
participant FavouritesService 

User -> UI : Нажатие кнопки

alt Компонент отсутствует в избранном
  UI -> FavouritesController : POST /favourites/add
  FavouritesController -> FavouritesService : addToFavourites
  FavouritesService -> FavouriteRepository : получил и отправил данные
  FavouriteRepository -> Database : Сохранение данных
else Компонент есть в иззбранном
  UI -> FavouritesController : DELETE /favourites/{id}
  FavouritesController -> FavouritesService : deleteFromFavourites
  FavouritesService -> FavouriteRepository : получил и отправил данные
  FavouriteRepository -> Database : Удаление успешно
end

Database -> FavouriteRepository : Результат записи
FavouriteRepository -> FavouritesService : Передача результата

alt Ошибка сохранения
  FavouritesService -> FavouritesController : Ошибка сохранения
else Успех
  FavouritesService -> FavouritesController : Сохранение успешно
end

FavouritesController -> UI : HTTP 2xx / HTTP 4xx / HTTP 5xx
UI -> User : Вывод ответа

@enduml
