#### C2. Container
@startuml

!include <c4/C4_Container.puml>

title Архитектура приложения СамСебеМеханик

Person(user, "Пользователь", "Зарегистрированный пользователь системы")

System_Boundary(system, "ВЕБ-приложение") {

    Container(backend, "Backend API", "Spring Boot (Java)", "REST API")

    ContainerDb(postgres, "Main Database", "PostgreSQL", "Хранит пользователей, компоненты, изображения, связи, избранное")

    ContainerDb(mongo, "Version Storage", "MongoDB", "Хранит версии описаний компонентов")

}

Rel(user, backend, "Использует", "HTTPS / JSON")

Rel(backend, postgres, "Читает/Пишет", "JPA / Hibernate")
Rel(backend, mongo, "Читает/Пишет", "Mongo Driver / Spring Data Mongo")

@enduml

#### C3. Componets
@startuml
!include <c4/C4_Component.puml>

title C4 Component Diagram — Catalog Service Backend (Ключевые бизнес-компоненты)

Person(client, "Клиент (Frontend / API consumer)", "Использует REST API")

Container_Boundary(backend, "Catalog Service (Spring Boot)") {

    Component(apiControllers, "Business REST Controllers", "Spring Web", "AutoComponentController, FavouriteController")

    Component(componentService, "AutoComponentServiceImpl", "Service", "Создание автокомпонентов")

    Component(favouriteService, "FavouriteServiceImpl", "Service", "Добавление и получение избранного")

    Component(versioningService, "AutoComponentVersioningService", "Service", "Версионирование описаний компонентов")

    Component(mappers, "DTO Mappers", "AutoComponentMapper, FavouriteMapper", "Преобразование Entity ↔ DTO")

    Component(componentRepo, "AutoComponentRepository", "Spring Data JPA", "CRUD для AutoComponent")

    Component(favouriteRepo, "FavouriteRepository", "Spring Data JPA", "CRUD и выборка избранного по userId")

    Component(versionRepo, "AutoComponentVersionRepository", "Spring Data MongoDB", "Хранение версий AutoComponentVersion")
}

ContainerDb(postgres, "PostgreSQL", "Relational DB", "auto_component, favourites")
ContainerDb(mongo, "MongoDB", "Document DB", "auto_component_versions")

Rel(client, apiControllers, "Вызывает endpoints", "HTTP/JSON")

Rel(apiControllers, componentService, "Использует")
Rel(apiControllers, favouriteService, "Использует")

Rel(componentService, componentRepo, "Сохраняет/читает AutoComponent")
Rel(componentService, mappers, "Формирует DTO")

Rel(favouriteService, favouriteRepo, "Сохраняет/читает Favourite")
Rel(favouriteService, componentRepo, "Проверяет существование компонента")
Rel(favouriteService, mappers, "Формирует DTO")

Rel(versioningService, componentRepo, "Читает/обновляет компонент")
Rel(versioningService, versionRepo, "Сохраняет версии")

Rel(componentRepo, postgres, "JPA/Hibernate")
Rel(favouriteRepo, postgres, "JPA/Hibernate")
Rel(versionRepo, mongo, "Spring Data MongoDB")

@enduml
